name: Test Env Config

on:

   workflow_dispatch:

jobs:

  DEV:
      runs-on: ubuntu-latest
      environment: Dev

      steps:
        - uses: action/checkout@v2

        - name: Run Script
          run: |
            echo "Running for Dev"

  QA:    
        runs-on: ubuntu-latest        
        environment: Prod
        
        steps:
           - uses: action/checkout@v2        
           - name: Run Script
             run: |
                    echo "Running for QA"

 
       
